datasets:
  - name: JSQuAD
    version: "1.1"
    split: valid
  # - name: MrTyDi
  #   version: "1.1"
  #   split: test
  #   sampling_method: "hard_negative"
  #   corpus_sample: 1000
  - name: MIRACL
    version: "1.0"
    split: dev
    sampling_method: "hard_negative"
    corpus_sample: 1000
#  - name: JSQuAD
#    version: "1.1"
#    split: train
embeddings:
  - name: SentenceTransformerEmbedding
    model_name: BAAI/bge-m3
  - name: E5Embedding
    model_name: intfloat/multilingual-e5-small
  - name: E5Embedding
    model_name: intfloat/multilingual-e5-base
  - name: E5Embedding
    model_name: intfloat/multilingual-e5-large
  # - name: CohereEmbedding
  #   model_name: embed-multilingual-light-v3.0
  # - name: CohereEmbedding
  #   model_name: embed-multilingual-v3.0
  # - name: VertexAITextEmbedding
  #   model_name: textembedding-gecko-multilingual@001
  # - name: VertexAITextEmbedding
  #   model_name: textembedding-gecko-multilingual@latest
  - name: SentenceTransformerEmbedding
    model_name: sonoisa/sentence-bert-base-ja-mean-tokens-v2
  - name: SentenceTransformerEmbedding
    model_name: pkshatech/GLuCoSE-base-ja
  - name: SentenceTransformerEmbedding
    model_name: cl-nagoya/sup-simcse-ja-base
  - name: SentenceTransformerEmbedding
    model_name: cl-nagoya/sup-simcse-ja-large
  - name: SentenceTransformerEmbedding
    model_name: cl-nagoya/unsup-simcse-ja-base
  - name: SentenceTransformerEmbedding
    model_name: cl-nagoya/unsup-simcse-ja-large
  # - name: OpenAIEmbedding
  #   model_name: text-embedding-ada-002
  - name: SonoisaSentenceBertJapanese
    model_name: sonoisa/sentence-bert-base-ja-mean-tokens-v2
  - name: SonoisaSentenceLukeJapanese
    model_name: sonoisa/sentence-luke-japanese-base-lite
late_interaction_retrievers:
  - name: ColBERTRetriever
    model_name: bclavie/JaColBERTv2
    n_gpu: 1
    overwrite: reuse
  - name: ColBERTRetriever
    model_name: bclavie/JaColBERT
    n_gpu: 1
    overwrite: reuse
relevances:
  - name: Cosine
#  - name: InnerProduct
#  - name: NegativeL2Distance
metrics:
  - name: Recall
    k: 1
  - name: Recall
    k: 3
  - name: Recall
    k: 5
  - name: Recall
    k: 10
  - name: Recall
    k : 100
